<?php

namespace garethp\ews\API\Message;

use garethp\ews\API\Message;

/**
 * Class representing ResponseMessageType
 *
 *
 * XSD Type: ResponseMessageType
 */
class ResponseMessageType extends Message
{

    /**
     * @var string
     */
    protected $responseClass = null;

    /**
     * @var string
     */
    protected $messageText = null;

    /**
     * @var string
     */
    protected $responseCode = null;

    /**
     * @var integer
     */
    protected $descriptiveLinkKey = null;

    /**
     * @var \garethp\ews\API\Message\ResponseMessageType\MessageXmlAType
     */
    protected $messageXml = null;

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getResponseClass()
    {
        return $this->responseClass;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ResponseMessageType
     */
    public function setResponseClass($value)
    {
        $this->responseClass = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getMessageText()
    {
        return $this->messageText;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ResponseMessageType
     */
    public function setMessageText($value)
    {
        $this->messageText = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getResponseCode()
    {
        return $this->responseCode;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ResponseMessageType
     */
    public function setResponseCode($value)
    {
        $this->responseCode = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return integer
     */
    public function getDescriptiveLinkKey()
    {
        return $this->descriptiveLinkKey;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value int
     * @return ResponseMessageType
     */
    public function setDescriptiveLinkKey($value)
    {
        $this->descriptiveLinkKey = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return \garethp\ews\API\Message\ResponseMessageType\MessageXmlAType
     */
    public function getMessageXml()
    {
        return $this->messageXml;
    }

    /**
     * The MessageXml element's XSD type is an anonymous complexType wrapping
     * xs:any, so SoapClient cannot map it to the classmap and hands over a
     * stdClass/array structure instead of a MessageXmlAType. Exchange only
     * attaches MessageXml to error responses (e.g. ErrorServerBusy), so a
     * strict type hint here turns every such error into a fatal TypeError
     * during response deserialization. Accept the raw structure and
     * normalize it, preserving the decoded values.
     *
     * @param $value \garethp\ews\API\Message\ResponseMessageType\MessageXmlAType|\stdClass|array|mixed
     * @return ResponseMessageType
     */
    public function setMessageXml($value)
    {
        if (!($value instanceof ResponseMessageType\MessageXmlAType)) {
            $value = ResponseMessageType\MessageXmlAType::fromUnmappedXml($value);
        }

        $this->messageXml = $value;
        return $this;
    }
}
